# Generated by Django 3.0 on 2022-04-15 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identification')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Time Created')),
                ('datetime_deleted', models.DateTimeField(auto_now=True, null=True, verbose_name='Time Deleted')),
                ('datetime_live', models.DateTimeField(auto_now=True, null=True, verbose_name='Time')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('todo', models.CharField(max_length=255, verbose_name='Задание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivnost')),
            ],
            options={
                'verbose_name': ('Задание',),
                'verbose_name_plural': 'Задание',
                'ordering': ('todo',),
            },
        ),
    ]
